language: minimal
script: asdf plugin-test concourse-fly https://github.com/ryodocx/asdf-concourse-fly
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
